//----------------------------------------------------------
// Do not edit this file directly. This is generated from
// Lumos color tokens & imported Momentum color tokens.
// src/components/${componentName}/tokens/*.js
// @momentum-ui/tokens/src/core/${componentName}.js
//----------------------------------------------------------

/* eslint-disable no-undef */
/* eslint-disable @typescript-eslint/no-var-requires */
const lmAccordionTokens = require("../../components/accordion/tokens/lm-accordion-tokens.js");
const mdAccordionTokens = require("../../components/accordion/tokens/md-accordion-tokens.js");
const lmAlertTokens = require("../../components/alert/tokens/lm-alert-tokens.js");
const mdAlertTokens = require("../../components/alert/tokens/md-alert-tokens.js");
const lmAlertbannerTokens = require("../../components/alert-banner/tokens/lm-alertbanner-tokens.js");
const mdAlertbannerTokens = require("../../components/alert-banner/tokens/md-alertbanner-tokens.js");
const lmAvatarTokens = require("../../components/avatar/tokens/lm-avatar-tokens.js");
const mdAvatarTokens = require("../../components/avatar/tokens/md-avatar-tokens.js");
const lmBadgeTokens = require("../../components/badge/tokens/lm-badge-tokens.js");
const mdBadgeTokens = require("../../components/badge/tokens/md-badge-tokens.js");
const lmBreadcrumbToken = require("../../components/breadcrumb/tokens/lm-breadcrumb-token.js");
const mdBreadcrumbToken = require("../../components/breadcrumb/tokens/md-breadcrumb-token.js");
const lmButtonTokens = require("../../components/button/tokens/lm-button-tokens.js");
const lmButtonGroupTokens = require("../../components/button-group/tokens/lm-button-group-tokens.js");
const mdButtonGroupTokens = require("../../components/button-group/tokens/md-button-group-tokens.js");
const lmChatMessageTokens = require("../../components/chat-message/tokens/lm-chat-message-tokens.js");
const mdChatMessageTokens = require("../../components/chat-message/tokens/md-chat-message-tokens.js");
const lmCheckboxTokens = require("../../components/checkbox/tokens/lm-checkbox-tokens.js");
const mdCheckboxTokens = require("../../components/checkbox/tokens/md-checkbox-tokens.js");
const lmCoachmarkTokens = require("../../components/coachmark/tokens/lm-coachmark-tokens.js");
const mdCoachmarkTokens = require("../../components/coachmark/tokens/md-coachmark-tokens.js");
const lmComboboxTokens = require("../../components/combobox/tokens/lm-combobox-tokens.js");
const mdComboboxTokens = require("../../components/combobox/tokens/md-combobox-tokens.js");
const lmDateRangePickerTokens = require("../../components/date-range-picker/tokens/lm-date-range-picker-tokens.js");
const mdDateRangePickerTokens = require("../../components/date-range-picker/tokens/md-date-range-picker-tokens.js");
const lmDatepickerTokens = require("../../components/datepicker/tokens/lm-datepicker-tokens.js");
const mdDatepickerTokens = require("../../components/datepicker/tokens/md-datepicker-tokens.js");
const lmDropdownTokens = require("../../components/dropdown/tokens/lm-dropdown-tokens.js");
const mdDropdownTokens = require("../../components/dropdown/tokens/md-dropdown-tokens.js");
const lmEditabletextfieldTokens = require("../../components/editable-textfield/tokens/lm-editabletextfield-tokens.js");
const mdEditabletextfieldTokens = require("../../components/editable-textfield/tokens/md-editabletextfield-tokens.js");
const lmFloatingModalTokens = require("../../components/floating-modal/tokens/lm-floating-modal-tokens.js");
const mdFloatingModalTokens = require("../../components/floating-modal/tokens/md-floating-modal-tokens.js");
const lmHelpTextTokens = require("../../components/help-text/tokens/lm-help-text-tokens.js");
const mdHelpTextTokens = require("../../components/help-text/tokens/md-help-text-tokens.js");
const lmInputTokens = require("../../components/input/tokens/lm-input-tokens.js");
const mdInputTokens = require("../../components/input/tokens/md-input-tokens.js");
const lmLabelTokens = require("../../components/label/tokens/lm-label-tokens.js");
const mdLabelTokens = require("../../components/label/tokens/md-label-tokens.js");
const lmLinkTokens = require("../../components/link/tokens/lm-link-tokens.js");
const mdLinkTokens = require("../../components/link/tokens/md-link-tokens.js");
const lmListTokens = require("../../components/list/tokens/lm-list-tokens.js");
const mdListTokens = require("../../components/list/tokens/md-list-tokens.js");
const lmMenuTokens = require("../../components/menu/tokens/lm-menu-tokens.js");
const mdMenuTokens = require("../../components/menu/tokens/md-menu-tokens.js");
const lmModalTokens = require("../../components/modal/tokens/lm-modal-tokens.js");
const mdModalTokens = require("../../components/modal/tokens/md-modal-tokens.js");
const lmPaginationTokens = require("../../components/pagination/tokens/lm-pagination-tokens.js");
const mdPaginationTokens = require("../../components/pagination/tokens/md-pagination-tokens.js");
const lmPhoneInputTokens = require("../../components/phone-input/tokens/lm-phone-input-tokens.js");
const mdPhoneInputTokens = require("../../components/phone-input/tokens/md-phone-input-tokens.js");
const lmRadioTokens = require("../../components/radio/tokens/lm-radio-tokens.js");
const mdRadioTokens = require("../../components/radio/tokens/md-radio-tokens.js");
const lmSliderToken = require("../../components/slider/tokens/lm-slider-token.js");
const mdSliderTokens = require("../../components/slider/tokens/md-slider-tokens.js");
const lmSpinnerTokens = require("../../components/spinner/tokens/lm-spinner-tokens.js");
const mdSpinnerTokens = require("../../components/spinner/tokens/md-spinner-tokens.js");
const lmTableTokens = require("../../components/table/tokens/lm-table-tokens.js");
const mdTableTokens = require("../../components/table/tokens/md-table-tokens.js");
const lmTableAdvancedTokens = require("../../components/table-advanced/tokens/lm-table-advanced-tokens.js");
const mdTableAdvancedTokens = require("../../components/table-advanced/tokens/md-table-advanced-tokens.js");
const lmTabsTokens = require("../../components/tabs/tokens/lm-tabs-tokens.js");
const mdTabsTokens = require("../../components/tabs/tokens/md-tabs-tokens.js");
const lmTaskitemTokens = require("../../components/taskitem/tokens/lm-taskitem-tokens.js");
const mdTaskitemTokens = require("../../components/taskitem/tokens/md-taskitem-tokens.js");
const lmToggleTokens = require("../../components/toggle-switch/tokens/lm-toggle-tokens.js");
const mdToggleTokens = require("../../components/toggle-switch/tokens/md-toggle-tokens.js");
const lmTooltipTokens = require("../../components/tooltip/tokens/lm-tooltip-tokens.js");
const mdTooltipTokens = require("../../components/tooltip/tokens/md-tooltip-tokens.js");

const tokenFiles = [
  lmAccordionTokens,
  mdAccordionTokens,
  lmAlertTokens,
  mdAlertTokens,
  lmAlertbannerTokens,
  mdAlertbannerTokens,
  lmAvatarTokens,
  mdAvatarTokens,
  lmBadgeTokens,
  mdBadgeTokens,
  lmBreadcrumbToken,
  mdBreadcrumbToken,
  lmButtonTokens,
  lmButtonGroupTokens,
  mdButtonGroupTokens,
  lmChatMessageTokens,
  mdChatMessageTokens,
  lmCheckboxTokens,
  mdCheckboxTokens,
  lmCoachmarkTokens,
  mdCoachmarkTokens,
  lmComboboxTokens,
  mdComboboxTokens,
  lmDateRangePickerTokens,
  mdDateRangePickerTokens,
  lmDatepickerTokens,
  mdDatepickerTokens,
  lmDropdownTokens,
  mdDropdownTokens,
  lmEditabletextfieldTokens,
  mdEditabletextfieldTokens,
  lmFloatingModalTokens,
  mdFloatingModalTokens,
  lmHelpTextTokens,
  mdHelpTextTokens,
  lmInputTokens,
  mdInputTokens,
  lmLabelTokens,
  mdLabelTokens,
  lmLinkTokens,
  mdLinkTokens,
  lmListTokens,
  mdListTokens,
  lmMenuTokens,
  mdMenuTokens,
  lmModalTokens,
  mdModalTokens,
  lmPaginationTokens,
  mdPaginationTokens,
  lmPhoneInputTokens,
  mdPhoneInputTokens,
  lmRadioTokens,
  mdRadioTokens,
  lmSliderToken,
  mdSliderTokens,
  lmSpinnerTokens,
  mdSpinnerTokens,
  lmTableTokens,
  mdTableTokens,
  lmTableAdvancedTokens,
  mdTableAdvancedTokens,
  lmTabsTokens,
  mdTabsTokens,
  lmTaskitemTokens,
  mdTaskitemTokens,
  lmToggleTokens,
  mdToggleTokens,
  lmTooltipTokens,
  mdTooltipTokens
];

const tokenFileNames = [
  "lm-accordion-tokens.js",
  "md-accordion-tokens.js",
  "lm-alert-tokens.js",
  "md-alert-tokens.js",
  "lm-alertbanner-tokens.js",
  "md-alertbanner-tokens.js",
  "lm-avatar-tokens.js",
  "md-avatar-tokens.js",
  "lm-badge-tokens.js",
  "md-badge-tokens.js",
  "lm-breadcrumb-token.js",
  "md-breadcrumb-token.js",
  "lm-button-tokens.js",
  "lm-button-group-tokens.js",
  "md-button-group-tokens.js",
  "lm-chat-message-tokens.js",
  "md-chat-message-tokens.js",
  "lm-checkbox-tokens.js",
  "md-checkbox-tokens.js",
  "lm-coachmark-tokens.js",
  "md-coachmark-tokens.js",
  "lm-combobox-tokens.js",
  "md-combobox-tokens.js",
  "lm-date-range-picker-tokens.js",
  "md-date-range-picker-tokens.js",
  "lm-datepicker-tokens.js",
  "md-datepicker-tokens.js",
  "lm-dropdown-tokens.js",
  "md-dropdown-tokens.js",
  "lm-editabletextfield-tokens.js",
  "md-editabletextfield-tokens.js",
  "lm-floating-modal-tokens.js",
  "md-floating-modal-tokens.js",
  "lm-help-text-tokens.js",
  "md-help-text-tokens.js",
  "lm-input-tokens.js",
  "md-input-tokens.js",
  "lm-label-tokens.js",
  "md-label-tokens.js",
  "lm-link-tokens.js",
  "md-link-tokens.js",
  "lm-list-tokens.js",
  "md-list-tokens.js",
  "lm-menu-tokens.js",
  "md-menu-tokens.js",
  "lm-modal-tokens.js",
  "md-modal-tokens.js",
  "lm-pagination-tokens.js",
  "md-pagination-tokens.js",
  "lm-phone-input-tokens.js",
  "md-phone-input-tokens.js",
  "lm-radio-tokens.js",
  "md-radio-tokens.js",
  "lm-slider-token.js",
  "md-slider-tokens.js",
  "lm-spinner-tokens.js",
  "md-spinner-tokens.js",
  "lm-table-tokens.js",
  "md-table-tokens.js",
  "lm-table-advanced-tokens.js",
  "md-table-advanced-tokens.js",
  "lm-tabs-tokens.js",
  "md-tabs-tokens.js",
  "lm-taskitem-tokens.js",
  "md-taskitem-tokens.js",
  "lm-toggle-tokens.js",
  "md-toggle-tokens.js",
  "lm-tooltip-tokens.js",
  "md-tooltip-tokens.js"
];

module.exports = {
  tokenFiles,
  tokenFileNames
};
